bot:
  api_key: uw sleutel
  command_prefix: /

modules:
  weather:
    enabled: true
    commands:
      get:
        description: Gets the current weather situation
        aliases:
        - currentweather
        - weather

services:
  weather:
    open_weather_api_key: