bot:
  api_key: uw sleutel
  command_prefix: /

modules:
  weather:
    enabled: true
    commands:
      get:
        description: Gets the current weather situation
        aliases:
          - currentweather
          - weather

  management:
    enabled: true
    commands:
      cleanmessages:
        description: This command cleans up messages in a channel
        aliases:
          - clean

services:
  weather:
    open_weather_api_key: